### ISSUE TITLE
get the correct replicability and pre-study probability

### ISSUE THREAD

**Issue by Yefeng0920** [Yefeng0920/stat_error_MA_git#1]
Hi Frantisek,

I just invited you to the repo and opened a github issue to discuss getting the correct replicability and pre-study probability.

I uploaded the R code for the pilot and corresponding data. I hope you can show me the right way.

ps: I will invite you to the effect size benchmark repo as well.

Best,
Yefeng

**Comment by Yefeng0920** [comment]
Hi Frantisek @FBartos,

As emphasized by Shinichi (I already invited him to the repo), we want to sort out your concern about calculating replicability and prior probability (or odds), so we set a Zoom meeting. 

In the `Rmd` named `CredibleScience_pilot`, you will find the code to compute replicability and prior probability. I also updated the analysis code incorporating your method of fitting a mixture model for signal-noise ratio. 

It would be great if you could have a look and provide the correct way to compute the two indices (if my way is wrong, which is likely) before our meeting. 

The main part of the manuscript is done as I sent it to you before. I really want to progress the writing of Methods section. So, if you can provide me with the correct way, I can update the values in the manuscript and go ahead with the writing.

Best wishes,
Yefeng

**Comment by FBartos** [comment]
Hi Yefeng, I will to take a look, but I won't have enough time to examine
it thoroughly before the meeting--sorry.
Frantisek

**Comment by Yefeng0920** [comment]
Hi @FBartos, I just sent the R code via email. You can also access it via this repo. Note that I am not properly trained in terms of coding or programming. So, my code might not look elegant. 

Cheers,
Yefeng
